ema = False
use_fp16 = False
seed = 6666
deterministic = True
log_level = 'INFO'
log_interval = 5
save_interval = 5
resume_from = None # resume with epoch 
load_from = None # load from just load train parameter with out scheduler or epoch.
finetune_from = None
debug=None
# debug=True